spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8090/
          predicates:
            - Path=/products/**
            - Path=/categories/**
        - id: r2
          uri: http://localhost:8091/
          predicates:
            - Path=/clients/**
            - Path=/orders/**
            - Path=/orderItems/**
       